#ifndef DARLING_LIBXML2_CONFIG_H
#define DARLING_LIBXML2_CONFIG_H

#define HAVE_SYS_TYPES_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_UNISTD_H 1
#define HAVE_FCNTL_H 1
#define HAVE_STDLIB_H 1
#define HAVE_MATH_H 1
#define HAVE_FLOAT_H 1
#define LIBXML_XPATH_ENABLED 1
#define LIBXML_OUTPUT_ENABLED 1
#define LIBXML_SCHEMAS_ENABLED 1
#define LIBXML_PATTERN_ENABLED 1
#define LIBXML_CATALOG_ENABLED 1
#define LIBXML_XINCLUDE_ENABLED 1
#define LIBXML_C14N_ENABLED 1
#define HAVE_ERRNO_H 1
#define HAVE_SYS_MMAN_H 1
#define HAVE_LIMITS_H 1
#define HAVE_PTHREAD_H 1
#define HAVE_CTYPE_H 1
#define HAVE_TIME_H 1
#define HAVE_SYS_SOCKET_H 1
#define HAVE_NETINET_IN_H 1
#define HAVE_ARPA_INET_H 1
#define HAVE_NETDB_H 1
#define HAVE_FCNTL_H 1
#define HAVE_SYS_SELECT_H 1
#define HAVE_SYS_SOCKET_H 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_STDARG_H 
#define HAVE_STRINGS_H 1
#define HAVE_VA_COPY 1
#define SEND_ARG2_CAST (const void*)
#define GETHOSTBYNAME_ARG_CAST (const char*)
#define _REENTRANT

#endif

